### ISSUE TITLE
quantify "sizable portion"

### ISSUE THREAD

**Issue by 0atman** [ryankemper/writings#5]
> A sizeable portion of those infected are either asymptomatic (no symptoms), or paucisymptomatic (few symptoms)

This is a very important fact that must be stated for the mitigation suggestions put forward in the article to have enough context for the reader to understand. 

If 1% of people are asymptomatic, say, then that makes self-isolation when you know you're sick possible, but if it's 10% or higher, it's a very different story. If it's a high percentage, that adds much more weight to a blanket shelter-in-place policy.

Can you find a couple of sources to get the estimated percentage?

https://github.com/ryankemper/writings/blame/master/The_Case_For_Ending_Lockdown.md#L21

**Comment by 0atman** [comment]
Oh wait, later on you link to the Vo paper (nice find, by the way, I'd not read that), which states:

>  Notably, 43.2% (95% CI 32.2-54.7%) of the confirmed SARS-CoV-2 infections detected across the two surveys were asymptomatic.

That's _crazy high_, why aren't we being told that!?

**Comment by ryankemper** [comment]
Will do. Thanks for all the feedback.

FWIW i think the % asymp. is very high. That’s why the proposal is _not_ to
practice containment. Aggressive testing of those around at-risk
individuals, everyone else lives more or less as normal besides
masks/distance and basically gets gradually infected by the pool of
asymptomatics.

BTW I will not make this part of the writeup since it’s so speculative but
logically the greater portion of transmission is from asymp., the greater
the selection pressure towards less virulent strains IF virulence is
correlated with symptoms.

I’ll be back near a “real” computer later tn and try to impl. some of the
feedback

**Comment by 0atman** [comment]
I hope you don't mind me proofreading and hitting you with all these issues - I'll try to break them into bitesized chunks!

I note that while everyone on HN was quick to comment, not one of them hit you with a PR or anything to help - which is dumb.

Expect more from me!

**Comment by ryankemper** [comment]
I love to see it. Thanks so much @0atman.

**Comment by 0atman** [comment]
No problem man, thanks for taking suggestions so well! :ok_hand:
