### ISSUE TITLE
Focus less on IMHE model

### ISSUE THREAD

**Issue by 0atman** [ryankemper/writings#7]
OK, the IMHE model may have problems, so what other models are there? It's not the only one. One bad flattened curve model doesn't invalidate them all.

One of the earliest thorough studies I have found was by [Imperial College](https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf) here in London, which is a REALLY good read, not as dense as many academic publications.

Are there examples of alternative models by other public health institutions?

**Comment by ryankemper** [comment]
Damn, the imperial college paper is really well written. I hadn't been exposed to it first-hand.

I think integrating some of the findings of that paper would really strengthen "my" argument significantly, or conversely would be solid evidence in favor of a different approach. Either outcome would be great in my book :P

I don't expect to be able to integrate it for another ~48 hours based on real-life stuff that will get in the way. But you are right, that is a really good read.

**Comment by 0atman** [comment]
It's amazing, right? And it was published SO early.
No probs man, I guess you're west-coast. 

I care only for facts, we can dig them out! :muscle:

**Comment by ryankemper** [comment]
Hey @0atman. It took me a bit, but I've finished the first iteration of revamping the approach to weighing each side.

See https://github.com/ryankemper/writings/pull/20; in short, Using Ferguson (and to a lesser extent Vo') we can extract some upper bounds on what a worst case scenario might look like for Pareto Mitigation. I think this allows us to give a much more balanced depiction of the possible paths we could take.

**Comment by ryankemper** [comment]
I'll probably deviate from the general recommendations for a pull-request-based workflow by merging to master before you get a chance to review, but if you're willing I'd definitely appreciate you looking over it whenever you have a bit of free time (we're in the middle of the work week, etc etc).

I'm sure there's plenty of improvements that could be made with these changes, but at least at first glance I think they will help a lot to assuage the very valid criticisms of "cherry-picked" data, etc.

**Comment by JerryLopatin** [comment]
Ryan,

 

I was circling back and reading your paper again for historical perspective.

 

Do you plan on writing an update or a retrospective?

 

Jerry

 

Jerry Lopatin

**Comment by ryankemper** [comment]
@JerryLopatin Hey Jerry.

I'd like to do either a retrospective or a more focused/streamlined v2 writeup. It's been hard to find motivation/time though, mainly because the state of political discourse here in the US is so shot that it stopped being about public health policy awhile ago. ...If it ever was...

Here in California Governer Newsom just released a new set of "guidelines" that guarantees California will stay locked down forever. I suspect that they will make some bullshit rule like "if 70% of the population in your county gets vaccinated then you can jump down to the minimal tier regardless of cases". The lowest tier is "minimal", represented by the color yellow, there is no green "back to normal" tier. They've abandoned both hospitalizations and deaths as metrics and are using just cases and case positivity rate, selected such that it is impossible to ever exit lockdown because to get the positivity rate down low enough you need to test enough such that the false positives alone would keep us locked down.

---

In retrospect, I think basically everything I predicted has come to pass, it's clear now that this pandemic was almost entirely an artifact of eroding the "pathological vs physiological distinction":


> Patient: Hey doc, I've got a coronavirus infection that is causing me no symptoms whatsoever, and overwhelming evidence points to the fact that I couldn't infect someone even if I tried

> Doctor: Open-and-shut case. You've got coronavirus *infectious* *disease* 2019.

> Patient: ...

---

Jerry, you mentioned PCR having a 20-30% false positivity rate way back when, and now we have evidence that it's closer to 90%, and thus the vast majority of positives are hitting on either (a) remnant viral debris in the absence of active infection, or (b) viable sars-2 but not in high enough amounts to infect another person. Primarily (a).

The entire concept of "asymptomatic COVID-19" is a sham, asymptomatic SARS-2 is real, asymptomatic COVID-19 is an oxymoron because it's neither a disease nor infectious if you're a true asymptomatic.

---

The presence of pre-existing T-cell cross reactivity in the majority of the population explains a lot about why some people seem to not infect others, and why there are probably some real asymptomatics (it's hard to say now because these asymptomatic cases could have been these fake PCR positives all along).

I had meant to update my writeup to mention the concept of heterogenous susceptibility as opposed to a simplistic homogenous view; heterogenity means that the true herd immunity threshold is lower than a simplistic model would predict. The presence of T-cell cross-reactivity further reduces the HIT. Many of us now think the HIT for covid is something like 15-20% seroprevalence.

---

As we all expected, Sweden had it right all along by not freaking out and losing their shit. Very jealous of their health leadership.

Living in a democrat-run state, masks are mandated indoors statewide, and were already mandated indoors at the county level. I see people wearing masks just to walk around in the open air by themselves.

Over time my views have only gotten more "radical": back when I did the writeup I still reluctantly advocated for suspending mass gatherings, I now think that no limits should be put on the general population whatsover. Universal masking is complete pseudoscience but if we assume it does slow transmission (I don't think it does) that's a bad thing since we should not slow the spread of SARS-2 in the general population.

I suspect about 90% of our recorded COVID deaths are basically a fabrication; someone died and happened to be PCR positive, but COVID didn't kill them. For those that did legitimately die of COVID, the years of life lost is quite small because COVID primarily kills the extremely old.

The universe where we never knew SARS-2 existed yet it emerged just the same is a universe with less poverty, more human rights, less all-cause mortality and likely less COVID-19 mortality.

Which reminds me on the other point I've gotten more radical on: I believe that lockdowns don't trade all-cause mortality to improve COVID-19 mortality; rather, I believe that lockdowns worsen both COVID-19 mortality and all-cause mortality, and thus are just a lose-lose situation.

The fact that we haven't reopened schools is completely laughable to me, and the fact that we are going to force kindergarten-aged kids to wear these disgusting masks and to undertake these reprehensible psychologically damaging social distancing measures is equally sad.

Hope things are going well for you all things considered.

Ryan
